#ifndef    RTE_COMPONENTS_H
#define    RTE_COMPONENTS_H
//=============================================================================

// Project:     CMSIS RTE Component Management
// Title:       RTE_Components.h
// Description: RTE Component Management Header File
//              This file contains the list of components and their base addresses
//              for the CMSIS RTE Component Management.
//              The components are defined in the RTE_Device.h file.
//              The RTE_Device.h file is generated by the RTE Device Configuration


#define CMSIS_device_header "RP2350.h"






#endif // RTE_COMPONENTS_H