
macro(pico_sdk_init)
if (NOT CMAKE_PROJECT_NAME)
    message(WARNING "pico_sdk_init() should be called after the project is created (and languages added)")
endif()
add_subdirectory(${PICO_SDK_PATH} pico-sdk)
endmacro()

macro(add_sub_list_dirs var)
foreach(LIST_DIR IN LISTS ${var})
    get_filename_component(SHORT_NAME "${LIST_DIR}" NAME)
    pico_message_debug("Including custom CMakeLists.txt ${SHORT_NAME}")
    add_subdirectory(${LIST_DIR} ${SHORT_NAME})
endforeach()
endmacro()

macro(add_sub_list_files var)
foreach(LIST_FILE IN LISTS ${var})
    pico_message_debug("Including custom CMake file ${LIST_FILE}")
    include(${LIST_FILE})
endforeach()
endmacro()

macro(pico_register_common_scope_var NAME)
if (NOT ${NAME} IN_LIST PICO_PROMOTE_COMMON_SCOPE_VARS)
    list(APPEND PICO_PROMOTE_COMMON_SCOPE_VARS ${NAME})
endif()
endmacro()

macro(pico_promote_common_scope_vars)
set(PICO_PROMOTE_COMMON_SCOPE_VARS ${PICO_PROMOTE_COMMON_SCOPE_VARS} PARENT_SCOPE)
foreach(VAR IN LISTS PICO_PROMOTE_COMMON_SCOPE_VARS)
    SET(${VAR} ${${VAR}} PARENT_SCOPE)
endforeach()
endmacro()